<x-persian-datepicker
    wirePropertyName="{{$name}}"
    label="{{$title}}"
    showFormat="{{$showFormat}}"
    returnFormat="X"
    :required="$required"
    :defaultDate="$defaultDate"
    :withTime="$setWithTime"
    :setNullInput="$setNullInput"
    :ignoreWire="$ignoreWire"
    :withTimeSeconds="$withTimeSeconds"/>
